### ISSUE TITLE
Odd 3rd text box on Add a New Tree page

### ISSUE THREAD

**Issue by andrewbt** [OpenTreeMap/otm-legacy#67] opened 2013-01-28 23:49 UTC
![Philly Tree Map](https://f.cloud.github.com/assets/2013555/105270/41e43eee-69a5-11e2-8da3-b1ea94e9e2f5.png)

The url is http://phillytreemap.org/trees/add/

This text box is unlabeled and doesn't seem to serve a function.

**Comment by andrewbt** [comment] 2013-01-28 23:57
Actually, this text box isn't totally rogue. After an address and city have been entered, and the map comes up with the "edit more tree details" boxes, this box appears awkwardly underneath the "Add this Tree!" button with the zip code of the address.

So it's the zip code box. But it's still off center and not showing up in the right places.

![Philly Tree Map-zipcode](https://f.cloud.github.com/assets/2013555/105299/72fa6480-69a6-11e2-847a-4e8fec1fdea1.png)

**Comment by jwalgran** [comment] 2013-01-29 13:39
My guess is that this box is supposed to be hidden and a style change made it visible. Thanks for the report.

**Comment by dboyer** [comment] 2013-04-01 16:39
This also appears on UrbanForestMap and GreenprintMaps. Perhaps it is related to the switch to support post code.

**Comment by steventlamb** [comment] 2013-04-03 20:30
In the "Hidden Fields" section of tree_add.html, https://github.com/azavea/OpenTreeMap/blob/v1.2/templates/treemap/tree_add.html#L171

All of these corresponding form fields have 'widget=forms.HiddenInput' except edit_address_zip. I've confirmed that adding this to the form field will make the field hidden in PTM and it looks like it should fix the others. I've also grepped to see if this field is used in other parts of the app, it's not.

The only consideration is that right now, however misplaced, this field does allow you to manually override the zip code that was populated by the address search. The user would no longer be able to do this. When the user goes back and edits the tree, they can edit the address, but not the zip code. Of course, this "feature" is not that useful, so, I'm assuming this is fine, but maybe someone else wants to weigh in?

**Comment by dboyer** [comment] 2013-04-04 14:04
I think it's fine to remove the option to edit zip code. In some OTM implementations, the address is actually not editable and just displays as whatever Google returns. I don't think it's necessary to include the option to edit the zip code.

**Comment by steventlamb** [comment] 2013-04-10 14:29
fixed in bf2066d12ccad458398bec9e21a66ef101b5de74

**Closed as completed by steventlamb** 2013-04-10 14:29 UTC
